// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAx7ekcLgxvH_2ZZTBoc9R-rDp6I5vj0M',
    appId: '1:829909632713:web:700b93512796cc77f52f18',
    messagingSenderId: '829909632713',
    projectId: 'smode-e4417',
    authDomain: 'smode-e4417.firebaseapp.com',
    storageBucket: 'smode-e4417.appspot.com',
    measurementId: 'G-0BVX1L84GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsQAcIucTGdIaOJ6bNsfkFTot-7od6Ad8',
    appId: '1:994591466792:android:c4b740dec5c82bff521c1d',
    messagingSenderId: '994591466792',
    projectId: 'smode-4dacc',
    storageBucket: 'smode-4dacc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvwnvbYxgcK-chL3Y22K4W4Yvb6pqMz7Y',
    appId: '1:829909632713:ios:16bdf2b02d3a661ef52f18',
    messagingSenderId: '829909632713',
    projectId: 'smode-e4417',
    storageBucket: 'smode-e4417.appspot.com',
    iosBundleId: 'com.example.smode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvwnvbYxgcK-chL3Y22K4W4Yvb6pqMz7Y',
    appId: '1:829909632713:ios:16bdf2b02d3a661ef52f18',
    messagingSenderId: '829909632713',
    projectId: 'smode-e4417',
    storageBucket: 'smode-e4417.appspot.com',
    iosBundleId: 'com.example.smode',
  );
}
